# Stage 1: Build

FROM maven:3.9.6-eclipse-temurin-21 AS build

LABEL maintainer="SAI KALYAN BURRA <kalyanw9700128@gmail.com> HealthCheck Service"

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests


# Stage 2: Production

FROM openjdk:21-slim

COPY --from=build /app/target/Authentication-0.0.1-SNAPSHOT.jar /app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app.jar"]
